### ISSUE TITLE
How to install/use?

### ISSUE THREAD

**Issue by SidDays** [Fronkln/LADFreecam#1]
Hi! Thank you so much for releasing your freecam mod! How exactly would I go about using it?

I tried installing it as a mod in SRMM (`LikeADragon8/runtime/media/mods/Freecam/Freecam.asi`), and also copying the `Freecam.asi` file to the `media/` folder, but I'm not sure how to use it.

To activate, I was trying the same keybind as [etra's freecam](https://github.com/etra0/yakuza-freecam) (RB+R3), but nothing happens in-game.

**Comment by Fronkln** [comment]
Installing it as a mod to mods/Freecam sounds right. when you open the game, a console window should pop up with the controls. Alt+M enables it for example.

**Comment by SidDays** [comment]
Ah, I didn't notice the console window with the instructions. It works great, thank you so much!
